<?php

namespace KK\StartBootStrapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getPosts()
    {
        return $this
            ->createQueryBuilder('post')
            ->addOrderBy('post.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }

}
